export const defaultAssets = {
    accessoryA: '/assets/AccessoryA/accessorya_000.png',
    accessoryB: '/assets/AccessoryB/accessoryb_000.png',
    accessoryC: '/assets/AccessoryC/accessoryc_000.png',
    accessoryD: '/assets/AccessoryD/accessoryd_000.png',
    arms: '/assets/Arms/arms_001.png',
    backA: '/assets/BackA/backa_000.png',
    body: '/assets/Body/body_001.png',
    bottomA: '/assets/BottomA/bottoma_001.png',
    bottomB: '/assets/BottomB/bottomb_000.png',
    ears: '/assets/Ears/ears_000.png',
    eyebrows: '/assets/Eyebrows/eyebrows_000.png',
    eyes: '/assets/Eyes/eyes_001.png',
    face: '/assets/Face/face_000.png',
    gloves: '/assets/Gloves/gloves_000.png',
    hairA: '/assets/HairA/haira_001.png',
    hairB: '/assets/HairB/hairb_000.png',
    hairC: '/assets/HairC/hairc_000.png',
    hairD: '/assets/HairD/haird_000.png',
    head: '/assets/Head/head_001.png',
    horns: '/assets/Horns/horns_000.png',
    jacketA: '/assets/JacketA/jacketa_000.png',
    jacketB: '/assets/JacketB/jacketb_000.png',
    mid: '/assets/Mid/mid_000.png',
    shoes: '/assets/Shoes/shoes_001.png',
    shoulderA: '/assets/ShoulderA/shouldera_000.png',
    shoulderB: '/assets/ShoulderB/shoulderb_000.png',
    socks: '/assets/Socks/socks_000.png',
    topA: '/assets/TopA/topa_001.png',
    topB: '/assets/TopB/topb_000.png',
}

export const assetRegistry = {
    accessoryA: [
        { id: 'accessorya_000', name: 'Accessory A 0', url: '/assets/AccessoryA/accessorya_000.png' },
        { id: 'accessorya_001', name: 'Accessory A 1', url: '/assets/AccessoryA/accessorya_001.png' },
        { id: 'accessorya_002', name: 'Accessory A 2', url: '/assets/AccessoryA/accessorya_002.png' },
        { id: 'accessorya_003', name: 'Accessory A 3', url: '/assets/AccessoryA/accessorya_003.png' },
        { id: 'accessorya_004', name: 'Accessory A 4', url: '/assets/AccessoryA/accessorya_004.png' },
        { id: 'accessorya_005', name: 'Accessory A 5', url: '/assets/AccessoryA/accessorya_005.png' },
        { id: 'accessorya_006', name: 'Accessory A 6', url: '/assets/AccessoryA/accessorya_006.png' },
    ],
    accessoryB: [
        { id: 'accessoryb_000', name: 'Accessory B 0', url: '/assets/AccessoryB/accessoryb_000.png' },
        { id: 'accessoryb_001', name: 'Accessory B 1', url: '/assets/AccessoryB/accessoryb_001.png' },
        { id: 'accessoryb_002', name: 'Accessory B 2', url: '/assets/AccessoryB/accessoryb_002.png' },
        { id: 'accessoryb_003', name: 'Accessory B 3', url: '/assets/AccessoryB/accessoryb_003.png' },
        { id: 'accessoryb_004', name: 'Accessory B 4', url: '/assets/AccessoryB/accessoryb_004.png' },
        { id: 'accessoryb_005', name: 'Accessory B 5', url: '/assets/AccessoryB/accessoryb_005.png' },
        { id: 'accessoryb_006', name: 'Accessory B 6', url: '/assets/AccessoryB/accessoryb_006.png' },
        { id: 'accessoryb_007', name: 'Accessory B 7', url: '/assets/AccessoryB/accessoryb_007.png' },
        { id: 'accessoryb_008', name: 'Accessory B 8', url: '/assets/AccessoryB/accessoryb_008.png' },
        { id: 'accessoryb_009', name: 'Accessory B 9', url: '/assets/AccessoryB/accessoryb_009.png' },
        { id: 'accessoryb_010', name: 'Accessory B 10', url: '/assets/AccessoryB/accessoryb_010.png' },
    ],
    accessoryC: [
        { id: 'accessoryc_000', name: 'Accessory C 0', url: '/assets/AccessoryC/accessoryc_000.png' },
        { id: 'accessoryc_001', name: 'Accessory C 1', url: '/assets/AccessoryC/accessoryc_001.png' },
        { id: 'accessoryc_002', name: 'Accessory C 2', url: '/assets/AccessoryC/accessoryc_002.png' },
        { id: 'accessoryc_003', name: 'Accessory C 3', url: '/assets/AccessoryC/accessoryc_003.png' },
        { id: 'accessoryc_004', name: 'Accessory C 4', url: '/assets/AccessoryC/accessoryc_004.png' },
        { id: 'accessoryc_005', name: 'Accessory C 5', url: '/assets/AccessoryC/accessoryc_005.png' },
        { id: 'accessoryc_006', name: 'Accessory C 6', url: '/assets/AccessoryC/accessoryc_006.png' },
        { id: 'accessoryc_007', name: 'Accessory C 7', url: '/assets/AccessoryC/accessoryc_007.png' },
        { id: 'accessoryc_008', name: 'Accessory C 8', url: '/assets/AccessoryC/accessoryc_008.png' },
        { id: 'accessoryc_009', name: 'Accessory C 9', url: '/assets/AccessoryC/accessoryc_009.png' },
    ],
    accessoryD: [
        { id: 'accessoryd_000', name: 'Accessory D 0', url: '/assets/AccessoryD/accessoryd_000.png' },
        { id: 'accessoryd_001', name: 'Accessory D 1', url: '/assets/AccessoryD/accessoryd_001.png' },
        { id: 'accessoryd_002', name: 'Accessory D 2', url: '/assets/AccessoryD/accessoryd_002.png' },
        { id: 'accessoryd_003', name: 'Accessory D 3', url: '/assets/AccessoryD/accessoryd_003.png' },
        { id: 'accessoryd_004', name: 'Accessory D 4', url: '/assets/AccessoryD/accessoryd_004.png' },
        { id: 'accessoryd_005', name: 'Accessory D 5', url: '/assets/AccessoryD/accessoryd_005.png' },
        { id: 'accessoryd_006', name: 'Accessory D 6', url: '/assets/AccessoryD/accessoryd_006.png' },
        { id: 'accessoryd_007', name: 'Accessory D 7', url: '/assets/AccessoryD/accessoryd_007.png' },
        { id: 'accessoryd_008', name: 'Accessory D 8', url: '/assets/AccessoryD/accessoryd_008.png' },
        { id: 'accessoryd_009', name: 'Accessory D 9', url: '/assets/AccessoryD/accessoryd_009.png' },
        { id: 'accessoryd_010', name: 'Accessory D 10', url: '/assets/AccessoryD/accessoryd_010.png' },
    ],
    arms: [
        { id: 'arms_001', name: 'Arms 1', url: '/assets/Arms/arms_001.png' },
        { id: 'arms_002', name: 'Arms 2', url: '/assets/Arms/arms_002.png' },
        { id: 'arms_003', name: 'Arms 3', url: '/assets/Arms/arms_003.png' },
    ],
    backA: [
        { id: 'backa_000', name: 'Back A 0', url: '/assets/BackA/backa_000.png' },
        { id: 'backa_001', name: 'Back A 1', url: '/assets/BackA/backa_001.png' },
        { id: 'backa_002', name: 'Back A 2', url: '/assets/BackA/backa_002.png' },
    ],
    body: [
        { id: 'body_001', name: 'Body', url: '/assets/Body/body_001.png' },
    ],
    bottomA: [
        { id: 'bottoma_001', name: 'Bottom A 1', url: '/assets/BottomA/bottoma_001.png' },
        { id: 'bottoma_002', name: 'Bottom A 2', url: '/assets/BottomA/bottoma_002.png' },
        { id: 'bottoma_003', name: 'Bottom A 3', url: '/assets/BottomA/bottoma_003.png' },
        { id: 'bottoma_004', name: 'Bottom A 4', url: '/assets/BottomA/bottoma_004.png' },
        { id: 'bottoma_005', name: 'Bottom A 5', url: '/assets/BottomA/bottoma_005.png' },
        { id: 'bottoma_006', name: 'Bottom A 6', url: '/assets/BottomA/bottoma_006.png' },
        { id: 'bottoma_007', name: 'Bottom A 7', url: '/assets/BottomA/bottoma_007.png' },
    ],
    bottomB: [
        { id: 'bottomb_000', name: 'Bottom B 0', url: '/assets/BottomB/bottomb_000.png' },
        { id: 'bottomb_001', name: 'Bottom B 1', url: '/assets/BottomB/bottomb_001.png' },
        { id: 'bottomb_002', name: 'Bottom B 2', url: '/assets/BottomB/bottomb_002.png' },
        { id: 'bottomb_003', name: 'Bottom B 3', url: '/assets/BottomB/bottomb_003.png' },
        { id: 'bottomb_004', name: 'Bottom B 4', url: '/assets/BottomB/bottomb_004.png' },
        { id: 'bottomb_005', name: 'Bottom B 5', url: '/assets/BottomB/bottomb_005.png' },
        { id: 'bottomb_006', name: 'Bottom B 6', url: '/assets/BottomB/bottomb_006.png' },
        { id: 'bottomb_007', name: 'Bottom B 7', url: '/assets/BottomB/bottomb_007.png' },
        { id: 'bottomb_008', name: 'Bottom B 8', url: '/assets/BottomB/bottomb_008.png' },
        { id: 'bottomb_009', name: 'Bottom B 9', url: '/assets/BottomB/bottomb_009.png' },
    ],
    ears: [
        { id: 'ears_000', name: 'Ears 0', url: '/assets/Ears/ears_000.png' },
        { id: 'ears_001', name: 'Ears 1', url: '/assets/Ears/ears_001.png' },
        { id: 'ears_002', name: 'Ears 2', url: '/assets/Ears/ears_002.png' },
        { id: 'ears_003', name: 'Ears 3', url: '/assets/Ears/ears_003.png' },
        { id: 'ears_004', name: 'Ears 4', url: '/assets/Ears/ears_004.png' },
    ],
    eyebrows: [
        { id: 'eyebrows_000', name: 'Eyebrows 0', url: '/assets/Eyebrows/eyebrows_000.png' },
        { id: 'eyebrows_001', name: 'Eyebrows 1', url: '/assets/Eyebrows/eyebrows_001.png' },
        { id: 'eyebrows_002', name: 'Eyebrows 2', url: '/assets/Eyebrows/eyebrows_002.png' },
        { id: 'eyebrows_003', name: 'Eyebrows 3', url: '/assets/Eyebrows/eyebrows_003.png' },
        { id: 'eyebrows_004', name: 'Eyebrows 4', url: '/assets/Eyebrows/eyebrows_004.png' },
        { id: 'eyebrows_005', name: 'Eyebrows 5', url: '/assets/Eyebrows/eyebrows_005.png' },
        { id: 'eyebrows_006', name: 'Eyebrows 6', url: '/assets/Eyebrows/eyebrows_006.png' },
    ],
    eyes: [
        { id: 'eyes_001', name: 'Eyes 1', url: '/assets/Eyes/eyes_001.png' },
        { id: 'eyes_002', name: 'Eyes 2', url: '/assets/Eyes/eyes_002.png' },
        { id: 'eyes_003', name: 'Eyes 3', url: '/assets/Eyes/eyes_003.png' },
        { id: 'eyes_004', name: 'Eyes 4', url: '/assets/Eyes/eyes_004.png' },
        { id: 'eyes_005', name: 'Eyes 5', url: '/assets/Eyes/eyes_005.png' },
        { id: 'eyes_006', name: 'Eyes 6', url: '/assets/Eyes/eyes_006.png' },
        { id: 'eyes_007', name: 'Eyes 7', url: '/assets/Eyes/eyes_007.png' },
        { id: 'eyes_008', name: 'Eyes 8', url: '/assets/Eyes/eyes_008.png' },
        { id: 'eyes_009', name: 'Eyes 9', url: '/assets/Eyes/eyes_009.png' },
        { id: 'eyes_010', name: 'Eyes 10', url: '/assets/Eyes/eyes_010.png' },
        { id: 'eyes_011', name: 'Eyes 11', url: '/assets/Eyes/eyes_011.png' },
        { id: 'eyes_012', name: 'Eyes 12', url: '/assets/Eyes/eyes_012.png' },
        { id: 'eyes_013', name: 'Eyes 13', url: '/assets/Eyes/eyes_013.png' },
        { id: 'eyes_014', name: 'Eyes 14', url: '/assets/Eyes/eyes_014.png' },
    ],
    face: [
        { id: 'face_000', name: 'Face 0', url: '/assets/Face/face_000.png' },
        { id: 'face_001', name: 'Face 1', url: '/assets/Face/face_001.png' },
        { id: 'face_002', name: 'Face 2', url: '/assets/Face/face_002.png' },
        { id: 'face_003', name: 'Face 3', url: '/assets/Face/face_003.png' },
    ],
    gloves: [
        { id: 'gloves_000', name: 'Gloves 0', url: '/assets/Gloves/gloves_000.png' },
        { id: 'gloves_001', name: 'Gloves 1', url: '/assets/Gloves/gloves_001.png' },
    ],
    hairA: [
        { id: 'haira_001', name: 'Hair A 1', url: '/assets/HairA/haira_001.png' },
        { id: 'haira_002', name: 'Hair A 2', url: '/assets/HairA/haira_002.png' },
        { id: 'haira_003', name: 'Hair A 3', url: '/assets/HairA/haira_003.png' },
        { id: 'haira_004', name: 'Hair A 4', url: '/assets/HairA/haira_004.png' },
        { id: 'haira_005', name: 'Hair A 5', url: '/assets/HairA/haira_005.png' },
        { id: 'haira_006', name: 'Hair A 6', url: '/assets/HairA/haira_006.png' },
        { id: 'haira_007', name: 'Hair A 7', url: '/assets/HairA/haira_007.png' },
        { id: 'haira_008', name: 'Hair A 8', url: '/assets/HairA/haira_008.png' },
        { id: 'haira_009', name: 'Hair A 9', url: '/assets/HairA/haira_009.png' },
        { id: 'haira_010', name: 'Hair A 10', url: '/assets/HairA/haira_010.png' },
        { id: 'haira_011', name: 'Hair A 11', url: '/assets/HairA/haira_011.png' },
        { id: 'haira_012', name: 'Hair A 12', url: '/assets/HairA/haira_012.png' },
        { id: 'haira_013', name: 'Hair A 13', url: '/assets/HairA/haira_013.png' },
        { id: 'haira_014', name: 'Hair A 14', url: '/assets/HairA/haira_014.png' },
        { id: 'haira_015', name: 'Hair A 15', url: '/assets/HairA/haira_015.png' },
        { id: 'haira_016', name: 'Hair A 16', url: '/assets/HairA/haira_016.png' },
    ],
    hairB: [
        { id: 'hairb_000', name: 'Hair B 0', url: '/assets/HairB/hairb_000.png' },
        { id: 'hairb_001', name: 'Hair B 1', url: '/assets/HairB/hairb_001.png' },
        { id: 'hairb_002', name: 'Hair B 2', url: '/assets/HairB/hairb_002.png' },
        { id: 'hairb_003', name: 'Hair B 3', url: '/assets/HairB/hairb_003.png' },
        { id: 'hairb_004', name: 'Hair B 4', url: '/assets/HairB/hairb_004.png' },
        { id: 'hairb_005', name: 'Hair B 5', url: '/assets/HairB/hairb_005.png' },
        { id: 'hairb_006', name: 'Hair B 6', url: '/assets/HairB/hairb_006.png' },
        { id: 'hairb_007', name: 'Hair B 7', url: '/assets/HairB/hairb_007.png' },
        { id: 'hairb_008', name: 'Hair B 8', url: '/assets/HairB/hairb_008.png' },
        { id: 'hairb_009', name: 'Hair B 9', url: '/assets/HairB/hairb_009.png' },
        { id: 'hairb_010', name: 'Hair B 10', url: '/assets/HairB/hairb_010.png' },
        { id: 'hairb_011', name: 'Hair B 11', url: '/assets/HairB/hairb_011.png' },
        { id: 'hairb_012', name: 'Hair B 12', url: '/assets/HairB/hairb_012.png' },
        { id: 'hairb_013', name: 'Hair B 13', url: '/assets/HairB/hairb_013.png' },
        { id: 'hairb_014', name: 'Hair B 14', url: '/assets/HairB/hairb_014.png' },
        { id: 'hairb_015', name: 'Hair B 15', url: '/assets/HairB/hairb_015.png' },
        { id: 'hairb_016', name: 'Hair B 16', url: '/assets/HairB/hairb_016.png' },
        { id: 'hairb_017', name: 'Hair B 17', url: '/assets/HairB/hairb_017.png' },
        { id: 'hairb_018', name: 'Hair B 18', url: '/assets/HairB/hairb_018.png' },
        { id: 'hairb_019', name: 'Hair B 19', url: '/assets/HairB/hairb_019.png' },
        { id: 'hairb_020', name: 'Hair B 20', url: '/assets/HairB/hairb_020.png' },
    ],
    hairC: [
        { id: 'hairc_000', name: 'Hair C 0', url: '/assets/HairC/hairc_000.png' },
        { id: 'hairc_001', name: 'Hair C 1', url: '/assets/HairC/hairc_001.png' },
        { id: 'hairc_002', name: 'Hair C 2', url: '/assets/HairC/hairc_002.png' },
        { id: 'hairc_003', name: 'Hair C 3', url: '/assets/HairC/hairc_003.png' },
        { id: 'hairc_004', name: 'Hair C 4', url: '/assets/HairC/hairc_004.png' },
        { id: 'hairc_005', name: 'Hair C 5', url: '/assets/HairC/hairc_005.png' },
        { id: 'hairc_006', name: 'Hair C 6', url: '/assets/HairC/hairc_006.png' },
        { id: 'hairc_007', name: 'Hair C 7', url: '/assets/HairC/hairc_007.png' },
        { id: 'hairc_008', name: 'Hair C 8', url: '/assets/HairC/hairc_008.png' },
        { id: 'hairc_009', name: 'Hair C 9', url: '/assets/HairC/hairc_009.png' },
        { id: 'hairc_010', name: 'Hair C 10', url: '/assets/HairC/hairc_010.png' },
        { id: 'hairc_011', name: 'Hair C 11', url: '/assets/HairC/hairc_011.png' },
        { id: 'hairc_012', name: 'Hair C 12', url: '/assets/HairC/hairc_012.png' },
        { id: 'hairc_013', name: 'Hair C 13', url: '/assets/HairC/hairc_013.png' },
        { id: 'hairc_014', name: 'Hair C 14', url: '/assets/HairC/hairc_014.png' },
        { id: 'hairc_015', name: 'Hair C 15', url: '/assets/HairC/hairc_015.png' },
        { id: 'hairc_016', name: 'Hair C 16', url: '/assets/HairC/hairc_016.png' },
        { id: 'hairc_017', name: 'Hair C 17', url: '/assets/HairC/hairc_017.png' },
        { id: 'hairc_018', name: 'Hair C 18', url: '/assets/HairC/hairc_018.png' },
        { id: 'hairc_019', name: 'Hair C 19', url: '/assets/HairC/hairc_019.png' },
        { id: 'hairc_020', name: 'Hair C 20', url: '/assets/HairC/hairc_020.png' },
        { id: 'hairc_021', name: 'Hair C 21', url: '/assets/HairC/hairc_021.png' },
        { id: 'hairc_022', name: 'Hair C 22', url: '/assets/HairC/hairc_022.png' },
    ],
    hairD: [
        { id: 'haird_000', name: 'Hair D 0', url: '/assets/HairD/haird_000.png' },
        { id: 'haird_001', name: 'Hair D 1', url: '/assets/HairD/haird_001.png' },
        { id: 'haird_002', name: 'Hair D 2', url: '/assets/HairD/haird_002.png' },
        { id: 'haird_003', name: 'Hair D 3', url: '/assets/HairD/haird_003.png' },
        { id: 'haird_004', name: 'Hair D 4', url: '/assets/HairD/haird_004.png' },
        { id: 'haird_005', name: 'Hair D 5', url: '/assets/HairD/haird_005.png' },
        { id: 'haird_006', name: 'Hair D 6', url: '/assets/HairD/haird_006.png' },
        { id: 'haird_007', name: 'Hair D 7', url: '/assets/HairD/haird_007.png' },
        { id: 'haird_008', name: 'Hair D 8', url: '/assets/HairD/haird_008.png' },
        { id: 'haird_009', name: 'Hair D 9', url: '/assets/HairD/haird_009.png' },
        { id: 'haird_010', name: 'Hair D 10', url: '/assets/HairD/haird_010.png' },
        { id: 'haird_011', name: 'Hair D 11', url: '/assets/HairD/haird_011.png' },
        { id: 'haird_012', name: 'Hair D 12', url: '/assets/HairD/haird_012.png' },
        { id: 'haird_013', name: 'Hair D 13', url: '/assets/HairD/haird_013.png' },
        { id: 'haird_014', name: 'Hair D 14', url: '/assets/HairD/haird_014.png' },
        { id: 'haird_015', name: 'Hair D 15', url: '/assets/HairD/haird_015.png' },
        { id: 'haird_016', name: 'Hair D 16', url: '/assets/HairD/haird_016.png' },
        { id: 'haird_017', name: 'Hair D 17', url: '/assets/HairD/haird_017.png' },
        { id: 'haird_018', name: 'Hair D 18', url: '/assets/HairD/haird_018.png' },
        { id: 'haird_019', name: 'Hair D 19', url: '/assets/HairD/haird_019.png' },
        { id: 'haird_020', name: 'Hair D 20', url: '/assets/HairD/haird_020.png' },
    ],
    head: [
        { id: 'head_001', name: 'Head', url: '/assets/Head/head_001.png' },
    ],
    horns: [
        { id: 'horns_000', name: 'Horns 0', url: '/assets/Horns/horns_000.png' },
        { id: 'horns_001', name: 'Horns 1', url: '/assets/Horns/horns_001.png' },
        { id: 'horns_002', name: 'Horns 2', url: '/assets/Horns/horns_002.png' },
        { id: 'horns_003', name: 'Horns 3', url: '/assets/Horns/horns_003.png' },
    ],
    jacketA: [
        { id: 'jacketa_000', name: 'Jacket A 0', url: '/assets/JacketA/jacketa_000.png' },
        { id: 'jacketa_001', name: 'Jacket A 1', url: '/assets/JacketA/jacketa_001.png' },
        { id: 'jacketa_002', name: 'Jacket A 2', url: '/assets/JacketA/jacketa_002.png' },
        { id: 'jacketa_003', name: 'Jacket A 3', url: '/assets/JacketA/jacketa_003.png' },
        { id: 'jacketa_004', name: 'Jacket A 4', url: '/assets/JacketA/jacketa_004.png' },
        { id: 'jacketa_005', name: 'Jacket A 5', url: '/assets/JacketA/jacketa_005.png' },
        { id: 'jacketa_006', name: 'Jacket A 6', url: '/assets/JacketA/jacketa_006.png' },
        { id: 'jacketa_007', name: 'Jacket A 7', url: '/assets/JacketA/jacketa_007.png' },
        { id: 'jacketa_008', name: 'Jacket A 8', url: '/assets/JacketA/jacketa_008.png' },
        { id: 'jacketa_009', name: 'Jacket A 9', url: '/assets/JacketA/jacketa_009.png' },
    ],
    jacketB: [
        { id: 'jacketb_000', name: 'Jacket B 0', url: '/assets/JacketB/jacketb_000.png' },
        { id: 'jacketb_001', name: 'Jacket B 1', url: '/assets/JacketB/jacketb_001.png' },
        { id: 'jacketb_002', name: 'Jacket B 2', url: '/assets/JacketB/jacketb_002.png' },
        { id: 'jacketb_003', name: 'Jacket B 3', url: '/assets/JacketB/jacketb_003.png' },
        { id: 'jacketb_004', name: 'Jacket B 4', url: '/assets/JacketB/jacketb_004.png' },
        { id: 'jacketb_005', name: 'Jacket B 5', url: '/assets/JacketB/jacketb_005.png' },
        { id: 'jacketb_006', name: 'Jacket B 6', url: '/assets/JacketB/jacketb_006.png' },
        { id: 'jacketb_007', name: 'Jacket B 7', url: '/assets/JacketB/jacketb_007.png' },
        { id: 'jacketb_008', name: 'Jacket B 8', url: '/assets/JacketB/jacketb_008.png' },
        { id: 'jacketb_009', name: 'Jacket B 9', url: '/assets/JacketB/jacketb_009.png' },
    ],
    mid: [
        { id: 'mid_000', name: 'Mid 0', url: '/assets/Mid/mid_000.png' },
        { id: 'mid_001', name: 'Mid 1', url: '/assets/Mid/mid_001.png' },
        { id: 'mid_002', name: 'Mid 2', url: '/assets/Mid/mid_002.png' },
        { id: 'mid_003', name: 'Mid 3', url: '/assets/Mid/mid_003.png' },
        { id: 'mid_004', name: 'Mid 4', url: '/assets/Mid/mid_004.png' },
        { id: 'mid_005', name: 'Mid 5', url: '/assets/Mid/mid_005.png' },
    ],
    shoes: [
        { id: 'shoes_001', name: 'Shoes 1', url: '/assets/Shoes/shoes_001.png' },
        { id: 'shoes_002', name: 'Shoes 2', url: '/assets/Shoes/shoes_002.png' },
        { id: 'shoes_003', name: 'Shoes 3', url: '/assets/Shoes/shoes_003.png' },
        { id: 'shoes_004', name: 'Shoes 4', url: '/assets/Shoes/shoes_004.png' },
    ],
    shoulderA: [
        { id: 'shouldera_000', name: 'Shoulder A 0', url: '/assets/ShoulderA/shouldera_000.png' },
        { id: 'shouldera_001', name: 'Shoulder A 1', url: '/assets/ShoulderA/shouldera_001.png' },
        { id: 'shouldera_002', name: 'Shoulder A 2', url: '/assets/ShoulderA/shouldera_002.png' },
        { id: 'shouldera_003', name: 'Shoulder A 3', url: '/assets/ShoulderA/shouldera_003.png' },
    ],
    shoulderB: [
        { id: 'shoulderb_000', name: 'Shoulder B 0', url: '/assets/ShoulderB/shoulderb_000.png' },
        { id: 'shoulderb_001', name: 'Shoulder B 1', url: '/assets/ShoulderB/shoulderb_001.png' },
        { id: 'shoulderb_002', name: 'Shoulder B 2', url: '/assets/ShoulderB/shoulderb_002.png' },
        { id: 'shoulderb_003', name: 'Shoulder B 3', url: '/assets/ShoulderB/shoulderb_003.png' },
    ],
    socks: [
        { id: 'socks_000', name: 'Socks 0', url: '/assets/Socks/socks_000.png' },
        { id: 'socks_001', name: 'Socks 1', url: '/assets/Socks/socks_001.png' },
        { id: 'socks_002', name: 'Socks 2', url: '/assets/Socks/socks_002.png' },
        { id: 'socks_003', name: 'Socks 3', url: '/assets/Socks/socks_003.png' },
    ],
    topA: [
        { id: 'topa_001', name: 'Top A 1', url: '/assets/TopA/topa_001.png' },
        { id: 'topa_002', name: 'Top A 2', url: '/assets/TopA/topa_002.png' },
        { id: 'topa_003', name: 'Top A 3', url: '/assets/TopA/topa_003.png' },
        { id: 'topa_004', name: 'Top A 4', url: '/assets/TopA/topa_004.png' },
        { id: 'topa_005', name: 'Top A 5', url: '/assets/TopA/topa_005.png' },
        { id: 'topa_006', name: 'Top A 6', url: '/assets/TopA/topa_006.png' },
        { id: 'topa_007', name: 'Top A 7', url: '/assets/TopA/topa_007.png' },
        { id: 'topa_008', name: 'Top A 8', url: '/assets/TopA/topa_008.png' },
        { id: 'topa_009', name: 'Top A 9', url: '/assets/TopA/topa_009.png' },
        { id: 'topa_010', name: 'Top A 10', url: '/assets/TopA/topa_010.png' },
        { id: 'topa_011', name: 'Top A 11', url: '/assets/TopA/topa_011.png' },
    ],
    topB: [
        { id: 'topb_000', name: 'Top B 0', url: '/assets/TopB/topb_000.png' },
        { id: 'topb_001', name: 'Top B 1', url: '/assets/TopB/topb_001.png' },
        { id: 'topb_002', name: 'Top B 2', url: '/assets/TopB/topb_002.png' },
        { id: 'topb_003', name: 'Top B 3', url: '/assets/TopB/topb_003.png' },
        { id: 'topb_004', name: 'Top B 4', url: '/assets/TopB/topb_004.png' },
        { id: 'topb_005', name: 'Top B 5', url: '/assets/TopB/topb_005.png' },
        { id: 'topb_006', name: 'Top B 6', url: '/assets/TopB/topb_006.png' },
        { id: 'topb_007', name: 'Top B 7', url: '/assets/TopB/topb_007.png' },
        { id: 'topb_008', name: 'Top B 8', url: '/assets/TopB/topb_008.png' },
        { id: 'topb_009', name: 'Top B 9', url: '/assets/TopB/topb_009.png' },
        { id: 'topb_010', name: 'Top B 10', url: '/assets/TopB/topb_010.png' },
        { id: 'topb_011', name: 'Top B 11', url: '/assets/TopB/topb_011.png' },
        { id: 'topb_012', name: 'Top B 12', url: '/assets/TopB/topb_012.png' },
        { id: 'topb_013', name: 'Top B 13', url: '/assets/TopB/topb_013.png' },
        { id: 'topb_014', name: 'Top B 14', url: '/assets/TopB/topb_014.png' },
        { id: 'topb_015', name: 'Top B 15', url: '/assets/TopB/topb_015.png' },
        { id: 'topb_016', name: 'Top B 16', url: '/assets/TopB/topb_016.png' },
        { id: 'topb_017', name: 'Top B 17', url: '/assets/TopB/topb_017.png' },
        { id: 'topb_018', name: 'Top B 18', url: '/assets/TopB/topb_018.png' },
        { id: 'topb_019', name: 'Top B 19', url: '/assets/TopB/topb_019.png' },
        { id: 'topb_020', name: 'Top B 20', url: '/assets/TopB/topb_020.png' },
        { id: 'topb_021', name: 'Top B 21', url: '/assets/TopB/topb_021.png' },
        { id: 'topb_022', name: 'Top B 22', url: '/assets/TopB/topb_022.png' },
        { id: 'topb_023', name: 'Top B 23', url: '/assets/TopB/topb_023.png' },
        { id: 'topb_024', name: 'Top B 24', url: '/assets/TopB/topb_024.png' },
        { id: 'topb_025', name: 'Top B 25', url: '/assets/TopB/topb_025.png' },
        { id: 'topb_026', name: 'Top B 26', url: '/assets/TopB/topb_026.png' },
        { id: 'topb_027', name: 'Top B 27', url: '/assets/TopB/topb_027.png' },
        { id: 'topb_028', name: 'Top B 28', url: '/assets/TopB/topb_028.png' },
        { id: 'topb_029', name: 'Top B 29', url: '/assets/TopB/topb_029.png' },
        { id: 'topb_030', name: 'Top B 30', url: '/assets/TopB/topb_030.png' },
    ],
}
